/*
 * SPDX-FileCopyrightText: Copyright (c) 2025-2026, NVIDIA CORPORATION & AFFILIATES. All rights
 * reserved. SPDX-License-Identifier: Apache-2.0
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#pragma once

#include <nvshmem.h>
#include <nvshmemx.h>
#include <rmm/cuda_device.hpp>

#include <cstdint>
#include <exception>
#include <memory>

namespace gqe {

/**
 * @brief Deleter for symmetric heap allocations made with nvshmem_malloc.
 */
struct nvshmem_deleter {
  void operator()(void* ptr) const
  {
    if (ptr) { nvshmem_free(ptr); }
  }
};

/**
 * @brief Owning pointer for a symmetric heap allocation.
 *
 * Uses @ref nvshmem_deleter to call `nvshmem_free` on destruction.
 *
 * @tparam T Element type.
 */
template <typename T>
using nvshmem_unique_ptr = std::unique_ptr<T, nvshmem_deleter>;

/**
 * @brief Allocate @p count elements on the NVSHMEM symmetric heap.
 *
 * @tparam T Element type.
 * @param count Number of elements to allocate (default 1).
 * @return An owning pointer to the allocation.
 * @throws std::runtime_error if `nvshmem_malloc` returns nullptr.
 */
template <typename T>
nvshmem_unique_ptr<T> make_nvshmem_unique(std::size_t count = 1)
{
  auto* ptr = static_cast<T*>(nvshmem_malloc(count * sizeof(T)));
  if (!ptr) { throw std::runtime_error("nvshmem_malloc failed"); }
  return nvshmem_unique_ptr<T>(ptr);
}

/**
 * @brief Abstract base class for communicators.
 */
struct communicator {
 public:
  virtual ~communicator() = default;
  virtual void init()     = 0;
  /**
   * @brief Finalize the communicator. Using the communicator after this call is undefined behavior.
   */
  virtual void finalize() = 0;
  /**
   * @brief Block until all ranks in the world have completed previously issues communication
   * operations.
   */
  virtual void barrier_world() = 0;
  /**
   * @brief Get the rank of the current process.
   */
  virtual int32_t rank() const = 0;
  /**
   * @brief Get the total number of ranks in the world.
   */
  virtual int32_t world_size() const = 0;
  /**
   * @brief Get the number of ranks per device.
   */
  virtual int32_t num_ranks_per_device() const = 0;

  /**
   * @brief Get the device id of the current process.
   */
  virtual rmm::cuda_device_id device_id() const = 0;

  /**
   * @brief Error propagation across ranks.
   */
  virtual void propagate_error(std::exception_ptr local_exception) const = 0;
};

/**
 * @brief Communicator backed by NVSHMEM, bootstrapped via a unique ID.
 *
 * Initialisation uses `NVSHMEMX_INIT_WITH_UNIQUEID` so that no MPI or PMIx
 * runtime is required. The unique ID is generated by rank 0 and distributed
 * to all ranks via gRPC through the node manager.
 *
 * Error propagation across ranks is implemented with a one-byte
 * `nvshmem_uint8_or_reduce` on symmetric-heap scratch buffers, replacing
 * the previous `MPI_Allreduce`.
 */
struct nvshmem_communicator : public communicator {
  /**
   * @brief Construct a new nvshmem_communicator.
   *
   * NVSHMEM is not initialised until @ref init() is called.
   *
   * @param rank   The rank assigned to this process (0-based).
   * @param nranks Total number of ranks in the world.
   * @param uid    128-byte unique ID shared by all ranks, obtained from
   *               `nvshmemx_get_uniqueid()` on rank 0.
   */
  nvshmem_communicator(int rank, int nranks, nvshmemx_uniqueid_t const& uid)
    : _init_rank(rank), _init_nranks(nranks), _uid(uid)
  {
  }
  void init() override;
  void finalize() override;
  void barrier_world() override;
  int32_t rank() const override { return _rank; }
  int32_t world_size() const override { return _size; }
  int32_t num_ranks_per_device() const override { return _ranks_per_device; }
  rmm::cuda_device_id device_id() const override { return _device_id; }
  void propagate_error(std::exception_ptr local_exception) const override;

 private:
  int _init_rank;
  int _init_nranks;
  nvshmemx_uniqueid_t _uid;
  int32_t _rank;
  int32_t _size;
  int32_t _ranks_per_device;
  rmm::cuda_device_id _device_id;
  nvshmem_unique_ptr<uint8_t> _err_local;
  nvshmem_unique_ptr<uint8_t> _err_global;
};
}  // namespace gqe
