/*
 * SPDX-FileCopyrightText: Copyright (c) 2022 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
 * SPDX-License-Identifier: LicenseRef-NvidiaProprietary
 *
 * NVIDIA CORPORATION, its affiliates and licensors retain all intellectual
 * property and proprietary rights in and to this material, related
 * documentation and any modifications thereto. Any use, reproduction,
 * disclosure or distribution of this material and related documentation
 * without an express license agreement from NVIDIA CORPORATION or
 * its affiliates is strictly prohibited.
 */

#pragma once

#include <gqe/executor/task.hpp>

#include <rmm/cuda_device.hpp>

#include <cstdint>
#include <string>
#include <variant>
#include <vector>

namespace gqe {

/**
 * @brief Enum to specify the type of a join.
 */
enum class join_type_type { inner, left, left_semi, left_anti, full, single };

/**
 * @brief List of input file formats.
 */
enum class file_format_type { parquet };

/**
 * @brief Strong type for a NUMA node indentifier.
 */
struct numa_node_id {
  using value_type = uint16_t;

  /**
   * @brief Construct a `numa_node_id` from the specified integer value.
   *
   * @param node_id The NUMA node's integer identifier.
   */
  explicit constexpr numa_node_id(value_type node_id) noexcept : _id(node_id) {}

  [[nodiscard]] constexpr value_type value() const noexcept { return _id; }

 private:
  value_type _id;
};

namespace storage_kind {

/**
 * @brief System memory allocated with the default system allocator.
 */
struct system_memory {
};

/**
 * @brief System memory allocated on a specific NUMA node.
 */
struct numa_memory {
  uint16_t numa_node; /**< NUMA node identifier hint. */
};

/**
 * @brief CUDA device memory.
 */
struct device_memory {
  rmm::cuda_device_id device_id; /**< CUDA device identifier hint. */
  cpu_set_t set;
};

/**
 * @brief Parquet file format, optionally Hive partitioned.
 */
struct parquet_file {
  std::vector<std::string> file_paths; /**< File paths. */
};

/**
 * @brief Storage kind of a table.
 *
 * The storage kind declares the physical representation of a table. For
 * example, the storage kind can be in-memory or a file. Some storage kinds also
 * take a location hint that specifies where the table should be stored, e.g.,
 * on which NUMA node.
 */
using type = std::variant<storage_kind::system_memory,
                          storage_kind::numa_memory,
                          storage_kind::device_memory,
                          storage_kind::parquet_file>;

}  // namespace storage_kind

namespace partitioning_schema_kind {

/**
 * @brief Automatic partitioning that infers the schema from the data.
 *
 * Inferrence of the partitioning schema is only possible for files. In-memory
 * storage defaults to `none`.
 */
struct automatic {
};

/**
 * @brief Do not partition data.
 */
struct none {
};

/**
 * @brief Key-by partitioning schema.
 *
 * The data are partitioned by key. Each unique key defines a partition.
 */
struct key {
  std::vector<std::string> columns; /**< Declare the key attributes. */
};

/**
 * @brief Partitioning schema kind of a table.
 *
 * The partitioning schema kind declares how records are assigned to table
 * partitions.
 */
using type = std::variant<partitioning_schema_kind::automatic,
                          partitioning_schema_kind::none,
                          partitioning_schema_kind::key>;

};  // namespace partitioning_schema_kind

/**
 * @brief Statistics of a table.
 */
struct table_statistics {
  int64_t num_rows;
};

/**
 * @brief Functor for generating tasks for user-defined relations.
 *
 * The first argument of the functor is a vector with the same length as the number of child
 * relations, where the `i`th element is a vector of tasks holding the output of the `i`th child
 * relation. These tasks serve as the input to the functor.
 *
 * The second argument is the task ID both as the input and as the output. When the functor
 * constructs a new task, it should use this argument as the task ID, and also increment this
 * argument.
 *
 * The third argument is the stage ID of the tasks generated by the functor.
 *
 * The return value of the functor is a vector of the output tasks.
 */
using user_defined_task_functor = std::function<std::vector<std::shared_ptr<task>>(
  std::vector<std::vector<std::shared_ptr<task>>>, int32_t&, int32_t)>;

}  // namespace gqe
