/*
 * SPDX-FileCopyrightText: Copyright (c) 2022 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
 * SPDX-License-Identifier: LicenseRef-NvidiaProprietary
 *
 * NVIDIA CORPORATION, its affiliates and licensors retain all intellectual
 * property and proprietary rights in and to this material, related
 * documentation and any modifications thereto. Any use, reproduction,
 * disclosure or distribution of this material and related documentation
 * without an express license agreement from NVIDIA CORPORATION or
 * its affiliates is strictly prohibited.
 */

#pragma once

#include <gqe/executor/task.hpp>

#include <cstdint>
#include <vector>

namespace gqe {

/**
 * @brief Enum to specify the type of a join.
 */
enum class join_type_type { inner, left, left_semi, left_anti, full, single };

/**
 * @brief List of input file formats.
 */
enum class file_format_type { parquet };

/**
 * @brief Statistics of a table.
 */
struct table_statistics {
  int64_t num_rows;
};

/**
 * @brief Functor for generating tasks for user-defined relations.
 *
 * The first argument of the functor is a vector with the same length as the number of child
 * relations, where the `i`th element is a vector of tasks holding the output of the `i`th child
 * relation. These tasks serve as the input to the functor.
 *
 * The second argument is the task ID both as the input and as the output. When the functor
 * constructs a new task, it should use this argument as the task ID, and also increment this
 * argument.
 *
 * The third argument is the stage ID of the tasks generated by the functor.
 *
 * The return value of the functor is a vector of the output tasks.
 */
using user_defined_task_functor = std::function<std::vector<std::shared_ptr<task>>(
  std::vector<std::vector<std::shared_ptr<task>>>, int32_t&, int32_t)>;

}  // namespace gqe
