/*
 * SPDX-FileCopyrightText: Copyright (c) 2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
 * SPDX-License-Identifier: Apache-2.0
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#pragma once

#include <gqe/expression/expression.hpp>

#include <ostream>
#include <string>
#include <string_view>

namespace gqe {

/**
 * @brief Format a GQE expression as a JSON string.
 *
 * The generated JSON string is contained in a single line, without extraneous white space or
 * indentation. It can be pretty printed and validated with an external tool such as
 * [jq](https://github.com/jqlang/jq).
 *
 * - Pretty print generated JSON: `echo <JSON> | jq .`
 * - Validate generated JSON: `echo <JSON> | jq empty; echo $?`
 *
 * Limitations:
 *
 * Only the unary_operator and binary_operator types contained in TPC-H partial
 * filters are explicitly supported, e.g., an `equal_expression` is represented as:
 *
 *     {"expression":"and_expression", ...}
 *
 * Unsupported unary_operator and binary_operator types are represented using the
 * casted int value of the enum.
 */
class expression_json_formatter : public expression_visitor {
 public:
  /**
   * Create a JSON formatter for GQE expression.
   * @param out The output stream to which the JSON representation is printed.
   */
  explicit expression_json_formatter(std::ostream& out);

  /**
   * @brief Serialize a GQE expression to a JSON string.
   * @param expression The GQE expression
   * @return A std::string containing the JSON representation of the expression.
   */
  static std::string to_json(const gqe::expression& expression);

  void visit(const literal_expression<int8_t>* expression) override;
  void visit(const literal_expression<int32_t>* expression) override;
  void visit(const literal_expression<int64_t>* expression) override;
  void visit(const literal_expression<float>* expression) override;
  void visit(const literal_expression<double>* expression) override;
  void visit(const literal_expression<std::string>* expression) override;
  void visit(const literal_expression<cudf::timestamp_D>* expression) override;
  void visit(const binary_op_expression* expression) override;
  void visit(const column_reference_expression* expression) override;
  void visit(const scalar_function_expression* expression) override;
  void visit(const unary_op_expression* expression) override;
  void visit(const subquery_expression* expression) override;
  void visit(const if_then_else_expression* expression) override;
  void visit(const cast_expression* expression) override;
  void visit(const is_null_expression* expression) override;

 private:
  /// Print open brace
  void open();

  /// Print close brace
  void close() const;

  /// Print a json key-value pair.
  void add_key_value_pair(std::string_view key, std::string_view value);

  /// Print a json key-value pair. The value is generated by calling value_serialization_functor,
  /// which directly manipulates the output stream _out.
  void add_key_value_pair(std::string_view key,
                          const std::function<void()>& value_serialization_functor);

  /// Print the expression type key-value pair, i.e., "expression":"expression_type".
  void add_expression_type_key_value_pair(std::string_view value);

  /// Format a literal expression as a JSON object.
  void add_literal_key_value_pair(const expression& expression, std::string_view value);

  /// The output stream to which the JSON data is printed.
  std::ostream& _out;

  /// Indicates that the first key-value pair has not yet been printed. If false, a comma will be
  /// printed before adding the next key-value pair.
  bool _isFirst;
};

}  // namespace gqe