stages:
  - test

variables:
  GQE_DEFAULT_IMAGE: "gitlab-master.nvidia.com:5005/devtech-compute/gqe:latest_x86_64"
  GQE_MR_IMAGE: "gitlab-master.nvidia.com:5005/devtech-compute/gqe:$CI_COMMIT_REF_SLUG"

  DOCKER_IMAGE: $GQE_DEFAULT_IMAGE

code_style:
  stage: test
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      changes: 
        - Dockerfile
        - conda/docker-aarch64.yml
        - conda/docker-x86_64.yml
      variables:
        DOCKER_IMAGE: $GQE_MR_IMAGE
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  image: $DOCKER_IMAGE
  before_script:
    - source /conda/bin/activate gqe
  script:
    - >
      find ./include ./src ./benchmark ./test -name *.hpp -o -name *.cpp -o -name *.cuh -o -name *.cu | xargs clang-format -style=file --dry-run -Werror ||
      { find ./include ./src ./benchmark ./test -name *.hpp -o -name *.cpp -o -name *.cuh -o -name *.cu | xargs clang-format -style=file -i; git diff | tee format_diff.patch; exit 1; }
  artifacts:
    paths:
      - format_diff.patch
    expire_in: 1 week
    when: on_failure

tpch_queries:
  stage: test
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      changes: 
        - Dockerfile
        - conda/docker-aarch64.yml
        - conda/docker-x86_64.yml
      variables:
        DOCKER_IMAGE: $GQE_MR_IMAGE
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  image: $DOCKER_IMAGE
  before_script:
    - source /conda/bin/activate gqe
  script:
    - hostname
    - nvidia-smi
    - export CCACHE_DIR=/ccache_files
    # For https links, the CI does not have access to the ssh keys, so we need to use deploy tokens.
    # Rather than have multiple deploy tokens for all dependencies, we use a single token for all dependencies, which is stored in the Variables section here: https://gitlab-master.nvidia.com/haog/gqe-python/-/settings/ci_cd.
    # Currently, the deploy token and username belongs to Yadu Kiran (ykiran)
    # TODO: Setup runner account for CI.
    - git config --global url."https://${GQE_NVCOMP_DEPLOY_USERNAME}:${GQE_NVCOMP_DEPLOY_TOKEN}@gitlab-master.nvidia.com/".insteadOf "https://gitlab-master.nvidia.com/"
    # Debug build
    # Disable the debug build for now because https://gitlab-master.nvidia.com/Devtech-Compute/gqe/-/blob/main/src/executor/groupby/hash_groupby.cuh?ref_type=heads#L556 would throw an invalid argument error under debug mode.
    #- rm -rf build
    #- mkdir build
    #- pushd build
    #- cmake -DCMAKE_BUILD_TYPE=Debug -DGQE_ENABLE_CUSTOMIZED_PARQUET=ON ..
    #- make -j30
    #- ctest --output-on-failure --exclude-regex parquet_reader
    #- popd
    # Release build
    - rm -rf build
    - mkdir build
    - pushd build
    - cmake -DGQE_ENABLE_CUSTOMIZED_PARQUET=ON -G Ninja ..
    - ninja -j30
    # Set the initial query memory to 2GiB for the tests.  This is enough and allows greater concurrency for the tests.
    - GQE_INITIAL_QUERY_MEMORY=$((2*1024*1024*1024)) ctest --output-on-failure --exclude-regex parquet_reader
    - popd
    # TPC-H coverage for SF1
    - GQE_INITIAL_QUERY_MEMORY=$((1024*1024*1024)) GQE_LOG_LEVEL=warn bash ./test/end_to_end/run_tpc.sh h ./build /tpch_scratch/datasets/sf0.01/sf0.01_id64/ /tpch_scratch/reference_results/sf0.01 /tpch_scratch/substrait_plans/sf0.01/df_q%d.bin
