/*
 * SPDX-FileCopyrightText: Copyright (c) 2022 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
 * SPDX-License-Identifier: LicenseRef-NvidiaProprietary
 *
 * NVIDIA CORPORATION, its affiliates and licensors retain all intellectual
 * property and proprietary rights in and to this material, related
 * documentation and any modifications thereto. Any use, reproduction,
 * disclosure or distribution of this material and related documentation
 * without an express license agreement from NVIDIA CORPORATION or
 * its affiliates is strictly prohibited.
 */

#pragma once

#include <gqe/logical/relation.hpp>

namespace gqe {
namespace optimizer {
class optimization_rule;
}  // namespace optimizer
namespace logical {

class project_relation : public relation {
  friend class gqe::optimizer::optimization_rule;

 public:
  /**
   * @brief Construct a new project relation object
   *
   * @param input_relation Input table to select columns from
   * @param subquery_relations Subquery relations that are referenced within the
   * `output_expressions`
   * @param output_expressions Expressions used for generating the new table. The generated
   * table contains the same number of columns as the length of `output_expressions`. The `i`th
   * column of the new table is generated by applying `output_expressions[i]` on `input`
   */
  project_relation(std::shared_ptr<relation> input_relation,
                   std::vector<std::shared_ptr<relation>> subquery_relations,
                   std::vector<std::unique_ptr<expression>> output_expressions);

  /**
   * @copydoc relation::type()
   */
  [[nodiscard]] relation_type type() const noexcept override { return relation_type::project; }

  /**
   * @copydoc relation::data_types()
   */
  [[nodiscard]] std::vector<cudf::data_type> data_types() const override;

  /**
   * @copydoc relation::to_string()
   */
  [[nodiscard]] std::string to_string() const override;

  /**
   * @brief Return a list of raw pointers to the output expressions.
   *
   * @return Vector of output expression raw pointers
   *
   * @note The returned expressions do not share ownership. This object must be kept alive for the
   * returned expressions to be valid.
   */
  [[nodiscard]] std::vector<expression*> output_expressions_unsafe() const
  {
    return gqe::utility::to_raw_ptrs(_output_expressions);
  }

  /**
   * @copydoc relation::operator==(const relation& other)
   */
  bool operator==(const relation& other) const override;

 private:
  //! List of one or more expressions to add to the input
  /*!
    This is usually used in SELECT and its order of selection.
  */
  std::vector<std::unique_ptr<expression>> _output_expressions;
};

}  // namespace logical
}  // namespace gqe