/*
 * SPDX-FileCopyrightText: Copyright (c) 2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
 * SPDX-License-Identifier: Apache-2.0
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#pragma once

#include <gqe/logical/relation.hpp>

namespace gqe {
namespace optimizer {
class optimization_rule;
}  // namespace optimizer
namespace logical {

class project_relation : public relation {
  friend class gqe::optimizer::optimization_rule;

 public:
  /**
   * @brief Construct a new project relation object
   *
   * @param input_relation Input table to select columns from
   * @param subquery_relations Subquery relations that are referenced within the
   * `output_expressions`
   * @param output_expressions Expressions used for generating the new table. The generated
   * table contains the same number of columns as the length of `output_expressions`. The `i`th
   * column of the new table is generated by applying `output_expressions[i]` on `input`
   */
  project_relation(std::shared_ptr<relation> input_relation,
                   std::vector<std::shared_ptr<relation>> subquery_relations,
                   std::vector<std::unique_ptr<expression>> output_expressions);

  /**
   * @copydoc relation::type()
   */
  [[nodiscard]] relation_type type() const noexcept override { return relation_type::project; }

  /**
   * @copydoc relation::data_types()
   */
  [[nodiscard]] std::vector<cudf::data_type> data_types() const override;

  /**
   * @copydoc relation::to_string()
   */
  [[nodiscard]] std::string to_string() const override;

  /**
   * @brief Return a list of raw pointers to the output expressions.
   *
   * @return Vector of output expression raw pointers
   *
   * @note The returned expressions do not share ownership. This object must be kept alive for the
   * returned expressions to be valid.
   */
  [[nodiscard]] std::vector<expression*> output_expressions_unsafe() const
  {
    return gqe::utility::to_raw_ptrs(_output_expressions);
  }

  /**
   * @brief Return a list of const raw pointers to the output expressions.
   *
   * @return Vector of const output expression raw pointers
   *
   * @note The returned expressions do not share ownership. This object must be kept alive for the
   * returned expressions to be valid.
   */
  [[nodiscard]] std::vector<expression const*> const_output_expressions_unsafe() const
  {
    return gqe::utility::to_const_raw_ptrs(_output_expressions);
  }

  /**
   * @copydoc relation::operator==(const relation& other)
   */
  bool operator==(const relation& other) const override;

  /**
   * @brief Replace the output expression at the specified index
   *
   * @param idx Index of the output expression to replace
   * @param new_expr The new expression to replace with
   */
  void replace_expr_at(cudf::size_type idx, std::unique_ptr<expression> new_expr)
  {
    assert(static_cast<std::size_t>(idx) < _output_expressions.size());
    _output_expressions[idx] = std::move(new_expr);
  }

 private:
  //! List of one or more expressions to add to the input
  /*!
    This is usually used in SELECT and its order of selection.
  */
  std::vector<std::unique_ptr<expression>> _output_expressions;
};

}  // namespace logical
}  // namespace gqe
