name: gqe
channels:
  - rapidsai
  - conda-forge
  - nvidia
dependencies:
  - libcudf=23.06
  - python=3.10
  - cudatoolkit=11.8
  - cmake
  - c-compiler
  - cxx-compiler
  - clang-tools=11.1.0
  - ptxcompiler
  - gcc_linux-64=11.*
  - sysroot_linux-64==2.17
  - nvcc_linux-64=11.8
