name: gqe
channels:
  - rapidsai
  - conda-forge
  - nvidia
dependencies:
  - cudf=22.12
  - python=3.9
  - cudatoolkit=11.5
  - cmake
  - c-compiler
  - cxx-compiler
  - clang-tools=11.1.0
  - ptxcompiler
  - gcc_linux-64=9.*
  - sysroot_linux-64==2.17
  - nvcc_linux-64=11.5
