name: gqe
channels:
  - rapidsai
  - conda-forge
  - nvidia
dependencies:
  - libcudf=23.06
  - libnuma
  - python=3.10
  - cuda-cccl=11.8
  - cuda-cudart=11.8
  - cuda-cudart-dev=11.8
  - cuda-nvcc=11.8
  - cmake
  - c-compiler
  - cxx-compiler
  - clang-tools=11.1.0
  - ptxcompiler
  - gcc_linux-64=11.*
  - sysroot_linux-64==2.17
  - libprotobuf=4.*
