/*
 * SPDX-FileCopyrightText: Copyright (c) 2023 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
 * SPDX-License-Identifier: LicenseRef-NvidiaProprietary
 *
 * NVIDIA CORPORATION, its affiliates and licensors retain all intellectual
 * property and proprietary rights in and to this material, related
 * documentation and any modifications thereto. Any use, reproduction,
 * disclosure or distribution of this material and related documentation
 * without an express license agreement from NVIDIA CORPORATION or
 * its affiliates is strictly prohibited.
 */

#include <gqe/utility/tpcds.hpp>

namespace gqe::utility {

namespace tpcds {

std::unordered_map<std::string, std::vector<column_definition_type>> const&
table_definitions() noexcept
{
  static const std::unordered_map<std::string, std::vector<column_definition_type>> definitions = {
    {"store_sales",
     {{"ss_sold_date_sk", identifier_type},
      {"ss_sold_time_sk", identifier_type},
      {"ss_item_sk", identifier_type},
      {"ss_customer_sk", identifier_type},
      {"ss_cdemo_sk", identifier_type},
      {"ss_hdemo_sk", identifier_type},
      {"ss_addr_sk", identifier_type},
      {"ss_store_sk", identifier_type},
      {"ss_promo_sk", identifier_type},
      {"ss_ticket_number", identifier_type},
      {"ss_quantity", integer_type},
      {"ss_wholesale_cost", decimal_type},
      {"ss_list_price", decimal_type},
      {"ss_sales_price", decimal_type},
      {"ss_ext_discount_amt", decimal_type},
      {"ss_ext_sales_price", decimal_type},
      {"ss_ext_wholesale_cost", decimal_type},
      {"ss_ext_list_price", decimal_type},
      {"ss_ext_tax", decimal_type},
      {"ss_coupon_amt", decimal_type},
      {"ss_net_paid", decimal_type},
      {"ss_net_paid_inc_tax", decimal_type},
      {"ss_net_profit", decimal_type}}},
    {"store_returns",
     {{"sr_returned_date_sk", identifier_type},
      {"sr_return_time_sk", identifier_type},
      {"sr_item_sk", identifier_type},
      {"sr_customer_sk", identifier_type},
      {"sr_cdemo_sk", identifier_type},
      {"sr_hdemo_sk", identifier_type},
      {"sr_addr_sk", identifier_type},
      {"sr_store_sk", identifier_type},
      {"sr_reason_sk", identifier_type},
      {"sr_ticket_number", identifier_type},
      {"sr_return_quantity", integer_type},
      {"sr_return_amt", decimal_type},
      {"sr_return_tax", decimal_type},
      {"sr_return_amt_inc_tax", decimal_type},
      {"sr_fee", decimal_type},
      {"sr_return_ship_cost", decimal_type},
      {"sr_refunded_cash", decimal_type},
      {"sr_reversed_charge", decimal_type},
      {"sr_store_credit", decimal_type},
      {"sr_net_loss", decimal_type}}},
    {"catalog_sales",
     {{"cs_sold_date_sk", identifier_type},
      {"cs_sold_time_sk", identifier_type},
      {"cs_ship_date_sk", identifier_type},
      {"cs_bill_customer_sk", identifier_type},
      {"cs_bill_cdemo_sk", identifier_type},
      {"cs_bill_hdemo_sk", identifier_type},
      {"cs_bill_addr_sk", identifier_type},
      {"cs_ship_customer_sk", identifier_type},
      {"cs_ship_cdemo_sk", identifier_type},
      {"cs_ship_hdemo_sk", identifier_type},
      {"cs_ship_addr_sk", identifier_type},
      {"cs_call_center_sk", identifier_type},
      {"cs_catalog_page_sk", identifier_type},
      {"cs_ship_mode_sk", identifier_type},
      {"cs_warehouse_sk", identifier_type},
      {"cs_item_sk", identifier_type},
      {"cs_promo_sk", identifier_type},
      {"cs_order_number", identifier_type},
      {"cs_quantity", integer_type},
      {"cs_wholesale_cost", decimal_type},
      {"cs_list_price", decimal_type},
      {"cs_sales_price", decimal_type},
      {"cs_ext_discount_amt", decimal_type},
      {"cs_ext_sales_price", decimal_type},
      {"cs_ext_wholesale_cost", decimal_type},
      {"cs_ext_list_price", decimal_type},
      {"cs_ext_tax", decimal_type},
      {"cs_coupon_amt", decimal_type},
      {"cs_ext_ship_cost", decimal_type},
      {"cs_net_paid", decimal_type},
      {"cs_net_paid_inc_tax", decimal_type},
      {"cs_net_paid_inc_ship", decimal_type},
      {"cs_net_paid_inc_ship_tax", decimal_type},
      {"cs_net_profit", decimal_type}}},
    {"catalog_returns",
     {{"cr_returned_date_sk", identifier_type},
      {"cr_returned_time_sk", identifier_type},
      {"cr_item_sk", identifier_type},
      {"cr_refunded_customer_sk", identifier_type},
      {"cr_refunded_cdemo_sk", identifier_type},
      {"cr_refunded_hdemo_sk", identifier_type},
      {"cr_refunded_addr_sk", identifier_type},
      {"cr_returning_customer_sk", identifier_type},
      {"cr_returning_cdemo_sk", identifier_type},
      {"cr_returning_hdemo_sk", identifier_type},
      {"cr_returning_addr_sk", identifier_type},
      {"cr_call_center_sk", identifier_type},
      {"cr_catalog_page_sk", identifier_type},
      {"cr_ship_mode_sk", identifier_type},
      {"cr_warehouse_sk", identifier_type},
      {"cr_reason_sk", identifier_type},
      {"cr_order_number", identifier_type},
      {"cr_return_quantity", integer_type},
      {"cr_return_amount", decimal_type},
      {"cr_return_tax", decimal_type},
      {"cr_return_amt_inc_tax", decimal_type},
      {"cr_fee", decimal_type},
      {"cr_return_ship_cost", decimal_type},
      {"cr_refunded_cash", decimal_type},
      {"cr_reversed_charge", decimal_type},
      {"cr_store_credit", decimal_type},
      {"cr_net_loss", decimal_type}}},
    {"web_sales",
     {{"ws_sold_date_sk", identifier_type},
      {"ws_sold_time_sk", identifier_type},
      {"ws_ship_date_sk", identifier_type},
      {"ws_item_sk", identifier_type},
      {"ws_bill_customer_sk", identifier_type},
      {"ws_bill_cdemo_sk", identifier_type},
      {"ws_bill_hdemo_sk", identifier_type},
      {"ws_bill_addr_sk", identifier_type},
      {"ws_ship_customer_sk", identifier_type},
      {"ws_ship_cdemo_sk", identifier_type},
      {"ws_ship_hdemo_sk", identifier_type},
      {"ws_ship_addr_sk", identifier_type},
      {"ws_web_page_sk", identifier_type},
      {"ws_web_site_sk", identifier_type},
      {"ws_ship_mode_sk", identifier_type},
      {"ws_warehouse_sk", identifier_type},
      {"ws_promo_sk", identifier_type},
      {"ws_order_number", identifier_type},
      {"ws_quantity", integer_type},
      {"ws_wholesale_cost", decimal_type},
      {"ws_list_price", decimal_type},
      {"ws_sales_price", decimal_type},
      {"ws_ext_discount_amt", decimal_type},
      {"ws_ext_sales_price", decimal_type},
      {"ws_ext_wholesale_cost", decimal_type},
      {"ws_ext_list_price", decimal_type},
      {"ws_ext_tax", decimal_type},
      {"ws_coupon_amt", decimal_type},
      {"ws_ext_ship_cost", decimal_type},
      {"ws_net_paid", decimal_type},
      {"ws_net_paid_inc_tax", decimal_type},
      {"ws_net_paid_inc_ship", decimal_type},
      {"ws_net_paid_inc_ship_tax", decimal_type},
      {"ws_net_profit", decimal_type}}},
    {"web_returns",
     {{"wr_returned_date_sk", identifier_type},
      {"wr_returned_time_sk", identifier_type},
      {"wr_item_sk", identifier_type},
      {"wr_refunded_customer_sk", identifier_type},
      {"wr_refunded_cdemo_sk", identifier_type},
      {"wr_refunded_hdemo_sk", identifier_type},
      {"wr_refunded_addr_sk", identifier_type},
      {"wr_returning_customer_sk", identifier_type},
      {"wr_returning_cdemo_sk", identifier_type},
      {"wr_returning_hdemo_sk", identifier_type},
      {"wr_returning_addr_sk", identifier_type},
      {"wr_web_page_sk", identifier_type},
      {"wr_reason_sk", identifier_type},
      {"wr_order_number", identifier_type},
      {"wr_return_quantity", integer_type},
      {"wr_return_amt", decimal_type},
      {"wr_return_tax", decimal_type},
      {"wr_return_amt_inc_tax", decimal_type},
      {"wr_fee", decimal_type},
      {"wr_return_ship_cost", decimal_type},
      {"wr_refunded_cash", decimal_type},
      {"wr_reversed_charge", decimal_type},
      {"wr_account_credit", decimal_type},
      {"wr_net_loss", decimal_type}}},
    {"inventory",
     {{"inv_date_sk", identifier_type},
      {"inv_item_sk", identifier_type},
      {"inv_warehouse_sk", identifier_type},
      {"inv_quantity_on_hand", integer_type}}},
    {"store",
     {
       {"s_store_sk", identifier_type},
       {"s_store_id", string_type},  // char(16)
       {"s_rec_start_date", date_type},
       {"s_rec_end_date", date_type},
       {"s_closed_date_sk", identifier_type},
       {"s_store_name", string_type},  // varchar(50)
       {"s_number_employees", integer_type},
       {"s_floor_space", integer_type},
       {"s_hours", string_type},    // char(20)
       {"s_manager", string_type},  // varchar(40)
       {"s_market_id", integer_type},
       {"s_geography_class", string_type},  // varchar(100)
       {"s_market_desc", string_type},      // varchar(100)
       {"s_market_manager", string_type},   // varchar(40)
       {"s_division_id", integer_type},
       {"s_division_name", string_type},  // varchar(50)
       {"s_company_id", integer_type},
       {"s_company_name", string_type},   // varchar(50)
       {"s_street_number", string_type},  // varchar(10)
       {"s_street_name", string_type},    // varchar(60)
       {"s_street_type", string_type},    // char(15)
       {"s_suite_number", string_type},   // char(10)
       {"s_city", string_type},           // varchar(60)
       {"s_county", string_type},         // varchar(30)
       {"s_state", string_type},          // char(2)
       {"s_zip", string_type},            // char(10)
       {"s_country", string_type},        // varchar(20)
       {"s_gmt_offset", decimal_type},
       {"s_tax_precentage",
        decimal_type}  // Note: spelling mistake in upstream data generator. See
                       // https://gitlab-master.nvidia.com/Devtech-Compute/gqe/-/merge_requests/114#note_16418623
     }},
    {"call_center",
     {{"cc_call_center_sk", identifier_type},
      {"cc_call_center_id", string_type},  // char(16)
      {"cc_rec_start_date", date_type},
      {"cc_rec_end_date", date_type},
      {"cc_closed_date_sk", identifier_type},
      {"cc_open_date_sk", identifier_type},
      {"cc_name", string_type},   // varchar(50)
      {"cc_class", string_type},  // varchar(50)
      {"cc_employees", integer_type},
      {"cc_sq_ft", integer_type},
      {"cc_hours", string_type},    // char(20)
      {"cc_manager", string_type},  // varchar(40)
      {"cc_mkt_id", integer_type},
      {"cc_mkt_class", string_type},       // char(50)
      {"cc_mkt_desc", string_type},        // varchar(100)
      {"cc_market_manager", string_type},  // varchar(40)
      {"cc_division", integer_type},
      {"cc_division_name", string_type},  // varchar(50)
      {"cc_company", integer_type},
      {"cc_company_name", string_type},   // char(50)
      {"cc_street_number", string_type},  // char(10)
      {"cc_street_name", string_type},    // varchar(60)
      {"cc_street_type", string_type},    // char(15)
      {"cc_suite_number", string_type},   // char(10)
      {"cc_city", string_type},           // varchar(60)
      {"cc_county", string_type},         // varchar(30)
      {"cc_state", string_type},          // char(2)
      {"cc_zip", string_type},            // char(10)
      {"cc_country", string_type},        // varchar(20)
      {"cc_gmt_offset", decimal_type},
      {"cc_tax_percentage", decimal_type}}},
    {"catalog_page",
     {{"cp_catalog_page_sk", identifier_type},
      {"cp_catalog_page_id", string_type},  // char(16)
      {"cp_start_date_sk", identifier_type},
      {"cp_end_date_sk", identifier_type},
      {"cp_department", string_type},  // varchar(50)
      {"cp_catalog_number", integer_type},
      {"cp_catalog_page_number", integer_type},
      {"cp_description", string_type},  // varchar(100)
      {"cp_type", string_type}}},       // varchar(100)
    {"web_site",
     {{"web_site_sk", identifier_type},
      {"web_site_id", string_type},
      {"web_rec_start_date", date_type},
      {"web_rec_end_date", date_type},
      {"web_name", string_type},
      {"web_open_date_sk", identifier_type},
      {"web_close_date_sk", identifier_type},
      {"web_class", string_type},
      {"web_manager", string_type},
      {"web_mkt_id", integer_type},
      {"web_mkt_class", string_type},
      {"web_mkt_desc", string_type},
      {"web_market_manager", string_type},
      {"web_company_id", integer_type},
      {"web_company_name", string_type},
      {"web_street_number", string_type},
      {"web_street_name", string_type},
      {"web_street_type", string_type},
      {"web_suite_number", string_type},
      {"web_city", string_type},
      {"web_county", string_type},
      {"web_state", string_type},
      {"web_zip", string_type},
      {"web_country", string_type},
      {"web_gmt_offset", decimal_type},
      {"web_tax_percentage", decimal_type}}},
    {"web_page",
     {{"wp_web_page_sk", identifier_type},
      {"wp_web_page_id", string_type},
      {"wp_rec_start_date", date_type},
      {"wp_rec_end_date", date_type},
      {"wp_creation_date_sk", identifier_type},
      {"wp_access_date_sk", identifier_type},
      {"wp_autogen_flag", string_type},
      {"wp_customer_sk", identifier_type},
      {"wp_url", string_type},
      {"wp_type", string_type},
      {"wp_char_count", integer_type},
      {"wp_link_count", integer_type},
      {"wp_image_count", integer_type},
      {"wp_max_ad_count", integer_type}}},
    {"warehouse",
     {{"w_warehouse_sk", identifier_type},
      {"w_warehouse_id", string_type},
      {"w_warehouse_name", string_type},
      {"w_warehouse_sq_ft", integer_type},
      {"w_street_number", string_type},
      {"w_street_name", string_type},
      {"w_street_type", string_type},
      {"w_suite_number", string_type},
      {"w_city", string_type},
      {"w_county", string_type},
      {"w_state", string_type},
      {"w_zip", string_type},
      {"w_country", string_type},
      {"w_gmt_offset", decimal_type}}},
    {"customer",
     {{"c_customer_sk", identifier_type},
      {"c_customer_id", string_type},
      {"c_current_cdemo_sk", identifier_type},
      {"c_current_hdemo_sk", identifier_type},
      {"c_current_addr_sk", identifier_type},
      {"c_first_shipto_date_sk", identifier_type},
      {"c_first_sales_date_sk", identifier_type},
      {"c_salutation", string_type},
      {"c_first_name", string_type},
      {"c_last_name", string_type},
      {"c_preferred_cust_flag", string_type},
      {"c_birth_day", integer_type},
      {"c_birth_month", integer_type},
      {"c_birth_year", integer_type},
      {"c_birth_country", string_type},
      {"c_login", string_type},
      {"c_email_address", string_type},
      // {"c_last_review_date_sk", identifier_type},
      {"c_last_review_date_sk", string_type}}},  // FIXME
    {"customer_address",
     {{"ca_address_sk", identifier_type},
      {"ca_address_id", string_type},
      {"ca_street_number", string_type},
      {"ca_street_name", string_type},
      {"ca_street_type", string_type},
      {"ca_suite_number", string_type},
      {"ca_city", string_type},
      {"ca_county", string_type},
      {"ca_state", string_type},
      {"ca_zip", string_type},
      {"ca_country", string_type},
      {"ca_gmt_offset", decimal_type},
      {"ca_location_type", string_type}}},
    {"customer_demographics",
     {{"cd_demo_sk", identifier_type},
      {"cd_gender", string_type},
      {"cd_marital_status", string_type},
      {"cd_education_status", string_type},
      {"cd_purchase_estimate", integer_type},
      {"cd_credit_rating", string_type},
      {"cd_dep_count", integer_type},
      {"cd_dep_employed_count", integer_type},
      {"cd_dep_college_count", integer_type}}},
    {"date_dim",
     {{"d_date_sk", identifier_type},
      {"d_date_id", string_type},
      {"d_date", date_type},
      {"d_month_seq", integer_type},
      {"d_week_seq", integer_type},
      {"d_quarter_seq", integer_type},
      {"d_year", integer_type},
      {"d_dow", integer_type},
      {"d_moy", integer_type},
      {"d_dom", integer_type},
      {"d_qoy", integer_type},
      {"d_fy_year", integer_type},
      {"d_fy_quarter_seq", integer_type},
      {"d_fy_week_seq", integer_type},
      {"d_day_name", string_type},
      {"d_quarter_name", string_type},
      {"d_holiday", string_type},
      {"d_weekend", string_type},
      {"d_following_holiday", string_type},
      {"d_first_dom", integer_type},
      {"d_last_dom", integer_type},
      {"d_same_day_ly", integer_type},
      {"d_same_day_lq", integer_type},
      {"d_current_day", string_type},
      {"d_current_week", string_type},
      {"d_current_month", string_type},
      {"d_current_quarter", string_type},
      {"d_current_year", string_type}}},
    {"household_demographics",
     {{"hd_demo_sk", identifier_type},
      {"hd_income_band_sk", identifier_type},
      {"hd_buy_potential", string_type},
      {"hd_dep_count", integer_type},
      {"hd_vehicle_count", integer_type}}},
    {"item", {{"i_item_sk", identifier_type},     {"i_item_id", string_type},
              {"i_rec_start_date", date_type},    {"i_rec_end_date", date_type},
              {"i_item_desc", string_type},       {"i_current_price", decimal_type},
              {"i_wholesale_cost", decimal_type}, {"i_brand_id", integer_type},
              {"i_brand", string_type},           {"i_class_id", integer_type},
              {"i_class", string_type},           {"i_category_id", integer_type},
              {"i_category", string_type},        {"i_manufact_id", integer_type},
              {"i_manufact", string_type},        {"i_size", string_type},
              {"i_formulation", string_type},     {"i_color", string_type},
              {"i_units", string_type},           {"i_container", string_type},
              {"i_manager_id", integer_type},     {"i_product_name", string_type}}},
    {"income_band",
     {{"ib_income_band_sk", identifier_type},
      {"ib_lower_bound", integer_type},
      {"ib_upper_bound", integer_type}}},
    {"promotion",
     {{"p_promo_sk", identifier_type},
      {"p_promo_id", string_type},
      {"p_start_date_sk", identifier_type},
      {"p_end_date_sk", identifier_type},
      {"p_item_sk", identifier_type},
      {"p_cost", decimal_type},  // should be decimal(15, 2)
      {"p_response_target", integer_type},
      {"p_promo_name", string_type},
      {"p_channel_dmail", string_type},
      {"p_channel_email", string_type},
      {"p_channel_catalog", string_type},
      {"p_channel_tv", string_type},
      {"p_channel_radio", string_type},
      {"p_channel_press", string_type},
      {"p_channel_event", string_type},
      {"p_channel_demo", string_type},
      {"p_channel_details", string_type},
      {"p_purpose", string_type},
      {"p_discount_active", string_type}}},
    {"reason",
     {{"r_reason_sk", identifier_type},
      {"r_reason_id", string_type},
      {"r_reason_desc", string_type}}},
    {"ship_mode",
     {{"sm_ship_mode_sk", identifier_type},
      {"sm_ship_mode_id", string_type},
      {"sm_type", string_type},
      {"sm_code", string_type},
      {"sm_carrier", string_type},
      {"sm_contract", string_type}}},
    {"time_dim",
     {{"t_time_sk", identifier_type},
      {"t_time_id", string_type},
      {"t_time", integer_type},
      {"t_hour", integer_type},
      {"t_minute", integer_type},
      {"t_second", integer_type},
      {"t_am_pm", string_type},
      {"t_shift", string_type},
      {"t_sub_shift", string_type},
      {"t_meal_time", string_type}}},
  };
  return definitions;
}

}  // namespace tpcds
}  // namespace gqe::utility
