#!/usr/bin/env python3

# SPDX-FileCopyrightText: Copyright (c) 2023 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: LicenseRef-NvidiaProprietary
#
# NVIDIA CORPORATION, its affiliates and licensors retain all intellectual
# property and proprietary rights in and to this material, related
# documentation and any modifications thereto. Any use, reproduction,
# disclosure or distribution of this material and related documentation
# without an express license agreement from NVIDIA CORPORATION or
# its affiliates is strictly prohibited.

"""
This script is used to parse the log generated by GQE to get the number of rows loaded. By default,
it parses the log from stdin. Note that `GQE_LOG_LEVEL` needs to be set to `trace`. For example,
$ GQE_LOG_LEVEL=trace <command-to-run-GQE> | ./parse_num_rows.py

Optionally, it can parse the log stored in a file. Please run `./parse_num_rows.py --help` for a
complete list of arguments.
"""

import argparse
import re


def main():
    arg_parser = argparse.ArgumentParser()
    arg_parser.add_argument("-f", "--file", help="location of the log file")
    args = arg_parser.parse_args()

    log_file_location = 0  # Default log file location to stdin
    if args.file:
        log_file_location = args.file

    column_names_to_num_rows = {}

    with open(log_file_location, mode="r") as log_file:
        pattern = re.compile(r"Load \[(.+)\] from files with (\d+) rows.")
        for line in log_file:
            match = pattern.search(line)
            if match is not None:
                column_names, num_rows = match.groups()
                if column_names not in column_names_to_num_rows:
                    column_names_to_num_rows[column_names] = int(num_rows)
                else:
                    column_names_to_num_rows[column_names] += int(num_rows)

    for column_names, num_rows in column_names_to_num_rows.items():
        print(f"[{column_names}]: {num_rows}")


if __name__ == "__main__":
    main()
