#!/usr/bin/env python3

# SPDX-FileCopyrightText: Copyright (c) 2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""
This script is used to parse the log generated by GQE to get the number of rows loaded. By default,
it parses the log from stdin. Note that `GQE_LOG_LEVEL` needs to be set to `trace`. For example,
$ GQE_LOG_LEVEL=trace <command-to-run-GQE> | ./parse_num_rows.py

Optionally, it can parse the log stored in a file. Please run `./parse_num_rows.py --help` for a
complete list of arguments.
"""

import argparse
import re


def main():
    arg_parser = argparse.ArgumentParser()
    arg_parser.add_argument("-f", "--file", help="location of the log file")
    args = arg_parser.parse_args()

    log_file_location = 0  # Default log file location to stdin
    if args.file:
        log_file_location = args.file

    column_names_to_num_rows = {}

    with open(log_file_location, mode="r") as log_file:
        pattern = re.compile(r"Load \[(.+)\] from files with (\d+) rows.")
        for line in log_file:
            match = pattern.search(line)
            if match is not None:
                column_names, num_rows = match.groups()
                if column_names not in column_names_to_num_rows:
                    column_names_to_num_rows[column_names] = int(num_rows)
                else:
                    column_names_to_num_rows[column_names] += int(num_rows)

    for column_names, num_rows in column_names_to_num_rows.items():
        print(f"[{column_names}]: {num_rows}")


if __name__ == "__main__":
    main()
