/*
 * SPDX-FileCopyrightText: Copyright (c) 2022 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
 * SPDX-License-Identifier: LicenseRef-NvidiaProprietary
 *
 * NVIDIA CORPORATION, its affiliates and licensors retain all intellectual
 * property and proprietary rights in and to this material, related
 * documentation and any modifications thereto. Any use, reproduction,
 * disclosure or distribution of this material and related documentation
 * without an express license agreement from NVIDIA CORPORATION or
 * its affiliates is strictly prohibited.
 */

#pragma once

#include <gqe/expression/expression.hpp>
#include <gqe/physical/relation.hpp>
#include <gqe/utility.hpp>

#include <memory>
#include <vector>

namespace gqe {

namespace physical {

/**
 * @brief Physical relation for generating a table by applying expressions on an existing table.
 */
class project_relation : public relation {
 public:
  /**
   * @brief Construct a new physical project relation.
   *
   * @param[in] input Input table on which `output_expressions` are applied.
   * @param[in] subquery_relations Subquery relations which are referenced by the expressions within
   * `output_expressions`.
   * @param[in] output_expressions Expressions used for generating the new table. The generated
   * table contains the same number of columns as the length of `output_expressions`. The `i`th
   * column of the new table is generated by applying `output_expressions[i]` on `input`.
   */
  project_relation(std::shared_ptr<relation> input,
                   std::vector<std::shared_ptr<relation>> subquery_relations,
                   std::vector<std::unique_ptr<expression>> output_expressions)
    : relation({std::move(input)}, subquery_relations),
      _output_expressions(std::move(output_expressions))
  {
  }

  /**
   * @copydoc gqe::physical::relation::accept(relation_visitor&)
   */
  void accept(relation_visitor& visitor) override { visitor.visit(this); }

  /**
   * @brief Return the expressions used for generating the new table.
   *
   * @note The returned expressions do not share ownership. This object needs to be kept alive for
   * the return expressions to be valid.
   */
  [[nodiscard]] std::vector<expression*> output_expressions_unsafe() const
  {
    return utility::to_raw_ptrs(_output_expressions);
  }

 private:
  std::vector<std::unique_ptr<expression>> _output_expressions;
};

}  // namespace physical
}  // namespace gqe
